### PR TITLE
fix list construction order

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by adrpo** [comment]
For sure there is a better way to do this, please check.

**Comment by sjoelund** [comment]
I think the listReverse isn't needed. Why not:

```julia
lst = nil()
for i in reverse
  lst = Cons(i, lst)
end
lst = Cons(a, Cons(b, lst))
```

**Comment by sjoelund** [comment]
Or perhaps more importantly; why do we need a specialization for more than 2 elements of list?

**Comment by adrpo** [comment]
> I think the listReverse isn't needed. Why not:
> 
> ```julia
> lst = nil()
> for i in reverse
>   lst = Cons(i, lst)
> end
> lst = Cons(a, Cons(b, lst))
> ```

Tried this but it complained about the nil binding.

**Comment by JKRT** [comment]
@adrpo  

Also please add a test that breaks on master but works with your changes. I have done so for most of the code I have added. CI/CD is not running yet but it is quite nice to explain the rationale for the changes

**Review by JKRT — CHANGES_REQUESTED** [review]
As stated in my comment. Please add a test illustrating why this change is needed

**Comment by adrpo** [comment]
A `const x = list(A, B, C, D, E)` will be stored as {C, D, E, A, B} without my first commit.
The second commit fixed this error:
```
ERROR: LoadError: MethodError: no method matching supertype(::Type{Union{Cons{EEquation}, Nil}})
Closest candidates are:
 supertype(::DataType) at operators.jl:44
 supertype(::UnionAll) at operators.jl:49
Stacktrace:
[1] _cons(::Cons{SCode.EEquation}, ::Cons{Union{Cons{EEquation}, Nil}}) at C:\home\adrpo33\dev\julia\ImmutableList.jl\src\list.jl:185
[2] translateEquation(::EQ_IF, ::SCode.COMMENT, ::SOURCEINFO, ::Bool) at C:\home\adrpo33\dev\julia\OMCompiler.jl\src\Frontend\AbsynToSCode.jl:1917
```

**Comment by adrpo** [comment]
I will see if I can add a test for the first commit

**Comment by JKRT** [comment]
> 
> 
> A `const x = list(A, B, C, D, E)` will be stored as {C, D, E, A, B} without my first commit.
> The second commit fixed this error:
> 
> ```
> ERROR: LoadError: MethodError: no method matching supertype(::Type{Union{Cons{EEquation}, Nil}})
> Closest candidates are:
>  supertype(::DataType) at operators.jl:44
>  supertype(::UnionAll) at operators.jl:49
> Stacktrace:
> [1] _cons(::Cons{SCode.EEquation}, ::Cons{Union{Cons{EEquation}, Nil}}) at C:\home\adrpo33\dev\julia\ImmutableList.jl\src\list.jl:185
> [2] translateEquation(::EQ_IF, ::SCode.COMMENT, ::SOURCEINFO, ::Bool) at C:\home\adrpo33\dev\julia\OMCompiler.jl\src\Frontend\AbsynToSCode.jl:1917
> ```

A, B, C, D, E are different types right? 

In that case simply write the test as 

```
abstract type ABS end

struct A <: ABS end 
....
@test  Cons<something something> == list(A, B, C, D)


```

**Comment by adrpo** [comment]
No, they are the same structured type, but different instances!

**Comment by adrpo** [comment]
This list was all mangled up:
https://github.com/JKRT/OMCompiler.jl/blob/master/src/Util/Flags.jl#L532
the first two elements, DEBUG and HELP were put at the end.

**Comment by JKRT** [comment]
> No, they are the same structured type, but different instances!

See above, I understood that. Basically a list of the supertype containing different subtypes but the order is messed up before this fix

**Review by JKRT — APPROVED** [review]

**Pull request merged**
