### PR TITLE
fail in some functions on empty lists

### PR DESCRIPTION
**Pull request by adrpo**
this adds a dependency on MetaModelica as we throw that exception, not sure if that is the correct way to do it

### CODE REVIEW

**Comment by JKRT** [comment]
@adrpo I agree with the change. However, I do not think we should add MetaModelica.jl as a dependency (We would also gain a circular dependency this way!).  Just throw some other exception instead

**Comment by sjoelund** [comment]
For MetaModelica code we would need to restructure matchcontinue to catch a union of errors I guess...

**Comment by adrpo** [comment]
Yes, this is why i throw a MM error, because otherwise is not caught by the fail semantics of matchcontinue. I guess one could check on some specific item in the thrown exception and rethrow if is not a MM exception.

**Comment by JKRT** [comment]
> 
> 
> Yes, this is why i throw a MM error, because otherwise is not caught by the fail semantics of matchcontinue. I guess one could check on some specific item in the thrown exception and rethrow if is not a MM exception.

MetaModelica.jl has a dependency on ImmutableList, so just introduce a custom error here as well and catch it over at MetaModelica.jl!

**Comment by adrpo** [comment]
Or we could just make a new package MetaModelicaExceptions that can be used by both

**Comment by JKRT** [comment]
> 
> 
> Or we could just make a new package MetaModelicaExceptions that can be used by both

I'd really like to have all the data structure stuff to be standing so alone as they can stand if possible. Then of course if we use something in MetaModelica.jl we can just add compatibility for it

**Comment by JKRT** [comment]
Hi,

Please see #9

**Pull request closed without merging**
